Feat/how it works section
PayStell/paystell-landing pull request #20
Opened 2024-12-20 03:42 UTC by kimcascante

# Pull Request Overview

## 📝 Summary
This PR implements an update for the "How it Works" section in third step to include animation more visible

### 🔗 Related Issues
- Closes #7 

## 🔄 Changes Made
I tried to update SVG image to make it fit as the figma design, but I just could change animation to be more visible, and I couldn't avoid the background image to fit in any resolution.

## 🖼️ Current Output
<img width="1424" alt="Captura de pantalla 2024-12-19 a la(s) 9 38 20 p  m" src="https://github.com/user-attachments/assets/04f6ce36-50c2-4b11-81db-d3f1d6cb1fff" />
![Captura de pantalla 2024-12-19 a la(s) 9 38 55 p  m](https://github.com/user-attachments/assets/abc6aa96-2343-4ce6-bbfc-54c88cc92acb)

## 🧪 Testing
I tried with different sizes, in different background positions. 

## 💬 Comments
Let me know if I can help with something else.

2024-12-20 16:20 UTC, MPSxDev commented
![image](https://github.com/user-attachments/assets/4caca7e1-7f75-4652-93b2-1088b78e15a2)
can you add some margin to this component please

2024-12-20 16:24 UTC, MPSxDev requested changes

2024-12-20 16:24 UTC, MPSxDev commented on src/components/sections/HowItWorks.tsx
![image](https://github.com/user-attachments/assets/c497d3cd-1dd5-4027-8254-43e4c4d95eae)
can you add some margin to this component please

2024-12-21 04:02 UTC, kimcascante commented on src/components/sections/HowItWorks.tsx
@MPSxDev done :) ! let me know

2024-12-21 14:58 UTC, MPSxDev approved these changes
Excellent, thanks @kimcascante

2024-12-21 14:58 UTC, merged